# Ammount of pixels to leave around the cropped area.
# Default: 10
padding = 10

# Increase this if gradients aren't being cut out properly.
# Default: 1
tolerance = 1

[exit_behavior]
always_pause = false
pause_on_error = true

[logging]
console_logging_level = "DEBUG"                                                           # DEBUG, INFO, WARNING, ERROR
file_logging_level = "DEBUG"                                                              # DEBUG, INFO, WARNING, ERROR
log_message_format = "%(asctime)s.%(msecs)03d %(levelname)s [%(funcName)s] - %(message)s"
logs_folder_name = "logs"
max_log_files = 50
